[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.footer_bar]
background = "#282a36"
foreground = "#f8f8f2"

[colors.hints.start]
background = "#f1fa8c"
foreground = "#282a36"

[colors.primary]
background = "#24292d"
bright_foreground = "#ffffff"
foreground = "#f8f8f2"

[colors.search.focused_match]
background = "#ffb86c"
foreground = "#44475a"

[colors.search.matches]
background = "#50fa7b"
foreground = "#44475a"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[font]
size = 12

[font.bold]
family = "Hack"

[font.italic]
family = "Hack"

[font.normal]
family = "Hack"
style = "Regular"

[window]
